#ifndef CLOUD_NOISE_GLSL
#define CLOUD_NOISE_GLSL

// https://www.shadertoy.com/view/3dVXDc
/**
    An implementation of tileable 3D Perlin-Worley noise for modeling volumetric clouds
    inspired from the chapter Real-Time Volumetric Cloudscapes by Andrew Schneider
    (Guerrilla Games). The first column is the perlin-worley noise generated by remapping
    perlin noise with the lowest frequency worley fbm. The next 3 columns are worley fbms
    with increasing frequencies, and are used to model the cloud shapes which are rendered
    in the last column. See the common tab for all the noise functions used.
*/

//vec3浮点向量，有3个float分量
//ivec3整数向量，3个int分量，访问分量u.x,u.y,u.z
//uvec无符号整数分量，3个uint分量
#define UI0 1597334673U//大整数种子
#define UI1 3812015801U//大整数种子
#define UI2 uvec2(UI0,UI1)//2D版
#define UI3 uvec3(UI0,UI1,2798796415U)//3D版
#define UIF (1.0/float(0xffffffffU))//把无符号整数缩放到[0,1]

vec3 hash33(vec3 p)//3D伪随机哈希函数
{
    uvec3 q=uvec3(ivec3(p))*UI3;//先无符号整数化，再用分量乘法打乱
    q=(q.x^q.y^q.z)*UI3;//按位异或再打乱
    return -1.+2.*vec3(q)*UIF;//映射到[-1,1]

}
//输入：空间位置 p（一般是格子坐标）
//输出：一个 vec3，分量大约在 [-1, 1] 之间
//特点：同一个 p 永远得到同一个结果，相邻 p 结果看起来随机、分布均匀。

//Gradient noise 3D梯度噪声，即Perlin噪声
float gradientNoise(vec3 x,float freq)//x为3D采样坐标，freq为周期长度
{
    //grid把空间切成单位立方体格子，看x落在哪个立方体格子上，并计算x在立方体格子的相对位置
    vec3 p=floor(x);//x所在格子左下角整数坐标
    vec3 w=fract(x);//格子内局部坐标，范围[0,1]

    //quintic interpolant五次插值曲线
    vec3 u=w*w*w*(w*(w*6.-15.)+10.);
    //在格子边界处让噪声值和变化率都平滑衔接，比线性插值更自然，Perlin 噪声的标准做法。

    //gradient
    vec3 ga=hash33(mod(p+vec3(0.,0.,0.),freq));//mod(p, freq) 的作用：让噪声在 freq 范围内循环，首尾能无缝拼接，方便烘焙进 3D 纹理
    vec3 gb = hash33(mod(p + vec3(1., 0., 0.), freq));
    vec3 gc = hash33(mod(p + vec3(0., 1., 0.), freq));
    vec3 gd = hash33(mod(p + vec3(1., 1., 0.), freq));
    vec3 ge = hash33(mod(p + vec3(0., 0., 1.), freq));
    vec3 gf = hash33(mod(p + vec3(1., 0., 1.), freq));
    vec3 gg = hash33(mod(p + vec3(0., 1., 1.), freq));
    vec3 gh = hash33(mod(p + vec3(1., 1., 1.), freq));
    //一个3D格子有8个顶点，每个顶点通过hash得到一个随机的方向ga到gh
    //设采样点对应的噪声值为f(x)
    //角点c函数值取0，把导数换成随机向量g，f(x)=f(c)+∇f(c)⋅(x−c)=0+g(w-角点)

    //projections
    float va = dot(ga, w - vec3(0., 0., 0.));
    float vb = dot(gb, w - vec3(1., 0., 0.));
    float vc = dot(gc, w - vec3(0., 1., 0.));
    float vd = dot(gd, w - vec3(1., 1., 0.));
    float ve = dot(ge, w - vec3(0., 0., 1.));
    float vf = dot(gf, w - vec3(1., 0., 1.));
    float vg = dot(gg, w - vec3(0., 1., 1.));
    float vh = dot(gh, w - vec3(1., 1., 1.));
    //对3d格子的每个角做点积，从角点到采样点的向量，投影到该角的随机梯度上
    //dot(g, w - 角点)，就是上述g*(w-角点)得到对应角点的f(x)
    

    //interpolation
    return va + 
        u.x * (vb - va) + 
        u.y * (vc - va) + 
        u.z * (ve - va) + 
        u.x * u.y * (va - vb - vc + vd) + 
        u.y * u.z * (va - vc - ve + vg) + 
        u.z * u.x * (va - vb - ve + vf) + 
        u.x * u.y * u.z * (-va + vb + vc - vd + ve - vf - vg + vh);
    //8个角各算出一个噪声值f(x)，但采样点对应噪声值只有一个值，用线性插值 w 在 x / y / z 三个方向上的相对位置决定每个角的权重，最终加权混合得到最终的噪声值
    //角{i，j,k}的权重={u.x(当i取1)[(1-u.x)当i取0]}*{u.y(j取1时)[(1-u.y)当j取1时]}*{u.z(k取1时)[(1-u.z)当k取0]}

}

//Tileable 3D Worley noise
float worleyNoise(vec3 uv,float freq)//uv是3D采样坐标，freq平铺周期(和Perlin一样)
{
    vec3 id =floor(uv);//在哪个格子
    vec3 p=fract(uv);//在这个格子哪里

    float minDist=10000.;//个人认为该值大于12即可
    for(float x=-1.;x<=1;++x)
    {
        for(float y=-1.;y<=1;++y)
        {
            for(float z=-1.;z<=1;++z)//考察27个邻居格子包括自己格子的所有候选特征点，如果采样点离自己所在格子边界较近，可能离邻居格子的特征点更加近
            {
                vec3 offset=vec3(x,y,z);
                vec3 h=hash33(mod(id+offset,vec3(freq)))*0.5+0.5;//每个格子里随机撒一个特征点，就是给格子id+offset生成一个随机向量，映射到[0,1]，表示特征点在该格子内部的相对位置
                h+=offset;//h相对自己所在格子的坐标改成相对采样点所在格子的坐标
                vec3 d=p-h;//计算采样点相对特征点的偏移向量
                minDist =min(minDist,dot(d,d));//minDist = 到27个候选特征点中最近那个的平方距离
            }
        }
    }

    return 1.-minDist;//反转Worley噪声
}

float perlinFbm(vec3 p,float freq,int octaves)//p 3D世界坐标 freq 第一层噪声的频率+平铺周期 octaves叠几层(层数越多，细节越丰富)
{
    float G=exp2(-0.85);//持久度，G小细节更弱，G大则更碎,取该值是经验上的平衡点
    float amp=1.0;//振幅
    float noise=0.0;
    for(int i=0;i<octaves;i++)
    {
        noise +=amp*gradientNoise(p*freq,freq);//p*freq是采样坐标缩放，控制细节粗细，缩放得越大，细节越细小；freq是平铺周期，越大周期越长
        freq*=2;//空间频率加倍，p*freq和freq变大，同样距离内格子更多，纹理更细
        amp*=G;//振幅按G衰减，细节权重更小，避免画面被噪点淹没
    }

    return noise;

}//分形Perlin噪声
//自相似：放大看仍有类似结构
//多尺度：大形 + 细节在同一函数里
//自然感：真实云、山、烟雾都有这种跨尺度结构

float worleyFbm(vec3 p,float freq)
{
    return worleyNoise(p*freq,freq)*0.625+
        worleyNoise(p*freq*2,freq*2)*0.25+
        worleyNoise(p*freq*4,freq*4)*0.125;
}//分形worley噪声,层数被写死三层



#endif


