// Auto-generated by tools/fetch_blue_noise_data.py — do not edit.
#pragma once

#include <cstdint>

namespace rs3d::blue_noise {

extern const uint32_t kSobol256spp256d[256 * 256];
extern const uint32_t kScramblingTile[128 * 128 * 8];
extern const uint32_t kRankingTile[128 * 128 * 8];

}  // namespace rs3d::blue_noise
