#!/usr/bin/env python3
"""Fetch / parse Heitz blue-noise tables (flower) into C++ data for shared_blue_noise.glsl."""
from __future__ import annotations

import argparse
import re
import sys
import urllib.request
from pathlib import Path

URL = (
    "https://raw.githubusercontent.com/qiutang98/flower/main/"
    "source/engine/util/samplerCPP/"
    "samplerBlueNoiseErrorDistribution_128x128_OptimizedFor_2d2d2d2d_256spp.cpp"
)
ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = ROOT / "src" / "render" / "data"
OUT_H = OUT_DIR / "blue_noise_sampler_data.h"


def fetch_url(url: str) -> str:
    print(f"Fetching {url}")
    req = urllib.request.Request(url, headers={"User-Agent": "RocketSim3D-fetch"})
    with urllib.request.urlopen(req, timeout=180) as resp:
        chunks: list[bytes] = []
        while True:
            chunk = resp.read(1 << 20)
            if not chunk:
                break
            chunks.append(chunk)
    return b"".join(chunks).decode("utf-8", errors="replace")


def parse_arrays(raw: str) -> dict[str, list[int]]:
    """Parse flower cpp: static const int name[...] = { ... };"""
    arrays: dict[str, list[int]] = {}
    pos = 0
    decl = re.compile(r"static\s+const\s+int\s+(\w+)\s*\[[^\]]+\]\s*=\s*\{", re.MULTILINE)
    while m := decl.search(raw, pos):
        name = m.group(1)
        i = m.end()
        depth = 1
        while i < len(raw) and depth:
            if raw[i] == "{":
                depth += 1
            elif raw[i] == "}":
                depth -= 1
            i += 1
        body = raw[m.end() : i - 1]
        vals = [int(x.strip(), 0) for x in body.split(",") if x.strip()]
        arrays[name] = vals
        print(f"  {name}: {len(vals)} ints")
        pos = i
    return arrays


def emit_array(cpp_name: str, vals: list[int]) -> str:
    lines = [f"alignas(16) const uint32_t {cpp_name}[{len(vals)}] = {{"]
    row = "    "
    for i, v in enumerate(vals):
        row += f"{v}u,"
        if (i + 1) % 16 == 0:
            lines.append(row)
            row = "    "
    if row.strip():
        lines.append(row)
    lines.append("};")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--input", type=Path, help="Local flower .cpp instead of download")
    args = ap.parse_args()

    if args.input:
        print(f"Reading {args.input}")
        raw = args.input.read_text(encoding="utf-8", errors="replace")
    else:
        try:
            raw = fetch_url(URL)
        except Exception as e:
            print(f"Download failed ({e}); try --input with a local flower sampler .cpp")
            return 1

    arrays = parse_arrays(raw)
    required = {
        "sobol": 256 * 256,
        "scrambling": 128 * 128 * 8,
        "ranking": 128 * 128 * 8,
    }
    by_size: dict[int, list[str]] = {}
    for name, vals in arrays.items():
        by_size.setdefault(len(vals), []).append(name)

    def pick(size: int, hint: str) -> str:
        cands = [n for n in by_size.get(size, []) if hint.lower() in n.lower()]
        if not cands:
            cands = by_size.get(size, [])
        if not cands:
            raise SystemExit(f"Missing array size {size} ({hint}). Found: {list(arrays)}")
        return cands[0]

    sobol_name = pick(required["sobol"], "sobol")
    scramble_name = pick(required["scrambling"], "scrambling")
    ranking_name = pick(required["ranking"], "ranking")

    OUT_DIR.mkdir(parents=True, exist_ok=True)

    files = [
        ("blue_noise_sobol.cpp", "kSobol256spp256d", arrays[sobol_name]),
        ("blue_noise_scrambling.cpp", "kScramblingTile", arrays[scramble_name]),
        ("blue_noise_ranking.cpp", "kRankingTile", arrays[ranking_name]),
    ]
    for fname, sym, vals in files:
        body = f"""// Auto-generated by tools/fetch_blue_noise_data.py — do not edit.
#include "blue_noise_sampler_data.h"

namespace rs3d::blue_noise {{

{emit_array(sym, vals)}

}}  // namespace rs3d::blue_noise
"""
        path = OUT_DIR / fname
        path.write_text(body, encoding="utf-8")
        print(f"Wrote {path} ({path.stat().st_size // 1024} KiB)")

    # Remove legacy monolithic TU if present.
    legacy = OUT_DIR / "blue_noise_sampler_data.cpp"
    if legacy.exists():
        legacy.unlink()
        print(f"Removed {legacy}")

    h = """// Auto-generated by tools/fetch_blue_noise_data.py — do not edit.
#pragma once

#include <cstdint>

namespace rs3d::blue_noise {

extern const uint32_t kSobol256spp256d[256 * 256];
extern const uint32_t kScramblingTile[128 * 128 * 8];
extern const uint32_t kRankingTile[128 * 128 * 8];

}  // namespace rs3d::blue_noise
"""
    OUT_H.write_text(h, encoding="utf-8")
    print(f"Wrote {OUT_H}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
